name: Playwright Automation

on:
  push:
    branches:
      - main
      - master

  pull_request:
    branches:
      - main
      - master
  workflow_dispatch:
    inputs:
      tags:
        description: "Cucumber tags"
        required: true
        default: "@smoke"

      workers:
        description: "Number of workers"
        required: true
        default: "2"

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - run: npm ci

      - run: npx playwright install --with-deps

      - name: Run Cucumber Tests
        run: |
          TAGS="${{ github.event.inputs.tags }}"
          WORKERS="${{ github.event.inputs.workers }}"
          npm run test -- --tags "$TAGS" --parallel "$WORKERS"
